apiVersion: mcsp.com/v1
kind: MinecraftServer
metadata:
  name: mc-eternal
spec:
  active: true
  server:
    id: mc-eternal
    image: itzg/minecraft-server:java8
    env:
      - name: TYPE
        value: FORGE
      - name: VERSION
        value: "1.12.2"
      - name: FORGE_VERSION
        value: "14.23.5.2860"
      - name: MEMORY
        value: 8G
  storage:
    capacity: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vanilla-minecraft-service
  labels:
    mcsp.com/serverId: vanilla-minecraft
spec:
  type: NodePort
  selector:
    mcsp.com/pod-role: runner
    mcsp.com/serverId: vanilla-minecraft
  ports:
  - name: tcp-minecraft
    protocol: TCP
    port: 25565
    targetPort: tcp-minecraft
    nodePort: 30565
