apiVersion: mcsp.com/v1
kind: MinecraftServer
metadata:
  name: test-server
spec:
  active: true
  server: 
    id: "test-server"
    jarfile: "server.jar"
    heapMax: 4096M
    heapInit: 4096M
  storage:
    capacity: 10Gi
