apiVersion: mcsp.com/v1
kind: MinecraftServer
metadata:
  name: vanilla-minecraft
spec:
  active: false
  server:
    id: vanilla-minecraft
    image: itzg/minecraft-server
    env:
      - name: MEMORY
        value: 4G
      - name: STOP_SERVER_ANNOUNCE_DELAY
        value: "10"
  storage:
    capacity: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vanilla-minecraft-service
  labels:
    mcsp.com/serverId: vanilla-minecraft
spec:
  type: NodePort
  selector:
    mcsp.com/pod-role: runner
    mcsp.com/serverId: vanilla-minecraft
  ports:
  - name: tcp-minecraft
    protocol: TCP
    port: 25565
    targetPort: tcp-minecraft
    nodePort: 32003
